name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  workflow_dispatch:

jobs:
  publish:
    name: Hugo Build and Publish
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup hugo context
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Caching modules
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Hugo build
        run: hugo --minify

      - name: Setup rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config
        run: echo "${{ secrets.RCLONE_CONFIG }}" > rclone.conf

      - name: Upload website content
        run: rclone --config rclone.conf sync ./public hosting:www/


